### ISSUE TITLE
不兼容dependencies配置

### ISSUE THREAD

**Issue by Sgenmi** [hyperf/nano#12]
是否可以兼容 dependencies配置

**Comment by Reasno** [comment]
兼容

**Comment by Sgenmi** [comment]
![image](https://user-images.githubusercontent.com/3337501/91920478-bec8d280-ecfb-11ea-8f0f-be295fc10974.png)
经测试，$this->get(\App\Services\Impl\EsInterface::class)  拿不到

**Comment by limingxinleo** [comment]
我试试看。。
