### ISSUE TITLE
env 不起作用

### ISSUE THREAD

**Issue by Sgenmi** [hyperf/nano#13]
![2FCD9FFC-3C2D-4431-8D8A-81E58D4EBEFF](https://user-images.githubusercontent.com/3337501/92224701-c1325480-eed4-11ea-9655-00dd7b96f764.png)

**Comment by Reasno** [comment]
要自己手动加载一下load env

**Comment by Sgenmi** [comment]
> 要自己手动加载一下load env

好的，3Q。留下代码

$dotenv = \Dotenv\Dotenv::createMutable(__DIR__);
$dotenv->load();
