### ISSUE TITLE
nano command命令怎么传参和接收参数

### ISSUE THREAD

**Issue by chenxi2015** [hyperf/nano#14]

**Comment by Reasno** [comment]
使用class方式注册command。闭包方式不支持传参数。

**Comment by ihipop** [comment]
@Reasno 这里class方式是 说的继承 `Hyperf\Command\Command` 实现handle这种方式么？我添加后没出现在命令列表里面

**Comment by yangguangwuwu** [comment]
https://hyperf.wiki/2.2/#/zh-cn/command?id=%e5%ae%9a%e4%b9%89%e5%91%bd%e4%bb%a4%e7%b1%bb%e7%9a%84%e5%8f%82%e6%95%b0
