### ISSUE TITLE
Adding middleware on $app->addRoute not gonna work

### ISSUE THREAD

**Issue by iqbalfn** [hyperf/nano#19]
As the title said, adding middlewares with `$app->addRoute($method, $path, $handler, ['middleware'=>[...]])` not gonna work because the script that add the middleware overwritten.

Please inspect [this line](https://github.com/hyperf/nano/blob/f783979ea1093f39257a766cd057cb3c97bc678a/src/App.php#L274)

```php
public function addRoute($httpMethod, string $route, $handler, array $options = [])
{
    // ...
    return $router->addRoute($httpMethod, $route, $handler, $options = []);
}
```

It should `return $router->addRoute($httpMethod, $route, $handler, $options);`.

**Comment by Reasno** [comment]
Thank you for reporting this bug. It will be fixed soon.
