### ISSUE TITLE
Websocket sample

### ISSUE THREAD

**Issue by ljfreelancer88** [hyperf/nano#26]
Hi, how can I make websocket working on Nano? An example please and thank you.

**Comment by huangdijia** [comment]
```php
$app = AppFactory::createBase('0.0.0.0', 9501);
$app->config(['server.servers.1' => [
        'name' => 'ws',
        'type' => Server::SERVER_WEBSOCKET,
        'host' => '0.0.0.0',
        'port' => 9502,
        'sock_type' => SWOOLE_SOCK_TCP,
        'callbacks' => [
            Event::ON_HAND_SHAKE => [\Hyperf\WebSocketServer\Server::class, 'onHandShake'],
            Event::ON_MESSAGE => [\Hyperf\WebSocketServer\Server::class, 'onMessage'],
            Event::ON_CLOSE => [\Hyperf\WebSocketServer\Server::class, 'onClose'],
        ],
    ],
]);
$app->run();
```

记得先安装 `hyperf/websocket-server`。

**Comment by as168795** [comment]
你好

> ```
> $app = AppFactory::createBase('0.0.0.0', 9501);
> $app->config(['server.servers.1' => [
>         'name' => 'ws',
>         'type' => Server::SERVER_WEBSOCKET,
>         'host' => '0.0.0.0',
>         'port' => 9502,
>         'sock_type' => SWOOLE_SOCK_TCP,
>         'callbacks' => [
>             Event::ON_HAND_SHAKE => [\Hyperf\WebSocketServer\Server::class, 'onHandShake'],
>             Event::ON_MESSAGE => [\Hyperf\WebSocketServer\Server::class, 'onMessage'],
>             Event::ON_CLOSE => [\Hyperf\WebSocketServer\Server::class, 'onClose'],
>         ],
>     ],
> ]);
> $app->run();
> ```
> 
> 记得先安装 `hyperf/websocket-server`。

你好，是否能提供更详细的实例
```php

use Hyperf\Nano\Factory\AppFactory;
use Hyperf\Server\Server;
use Hyperf\Server\Event;
require_once __DIR__ . '/vendor/autoload.php';

$app = AppFactory::createBase('0.0.0.0', 9503);
$app->config(['server.servers.1' => [
        'name' => 'ws',
        'type' => Server::SERVER_WEBSOCKET,
        'host' => '0.0.0.0',
        'port' => 9502,
        'sock_type' => SWOOLE_SOCK_TCP,
        'callbacks' => [
            Event::ON_HAND_SHAKE => [\Hyperf\WebSocketServer\Server::class, 'onHandShake'],
            Event::ON_MESSAGE => [\Hyperf\WebSocketServer\Server::class, 'onMessage'],
            Event::ON_CLOSE => [\Hyperf\WebSocketServer\Server::class, 'onClose'],
        ],
    ],
]);
$app->run();
```
我在使用上述代码时运行服务正常，但网页端建立链接时报错：

[DEBUG] WebSocket: fd[4] start a handshake request.
[WARNING] Hyperf\HttpMessage\Exception\NotFoundHttpException: Not Found(0) in /data/project/vendor/hyperf/http-server/src/CoreMiddleware.php:173

**Comment by huangdijia** [comment]
参考：https://github.com/huangdijia/nano-demo/commit/f0f143dfbc9de28a9f92ea6525cbd59231624e12

**Comment by as168795** [comment]
好的，非常感谢
