### ISSUE TITLE
升级 hyperf 2.2，启动项目报错

### ISSUE THREAD

**Issue by zhenggg** [hyperf/nano#27]
php 版本：8.0.8

启动项目报错如下：
PHP Fatal error:  Declaration of Hyperf\Nano\ContainerProxy::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /www/wwwroot/test/test_nano_v2.2/vendor/hyperf/nano/src/ContainerProxy.php on line 57

**Comment by huangzhhui** [comment]
Nano 暂时还没支持 2.2，我们尽快处理一下
