### ISSUE TITLE
无法使用config()自定义log_level

### ISSUE THREAD

**Issue by xiaoguo0426** [hyperf/nano#3]
`
$app->config([
    StdoutLoggerInterface::class => [
        'log_level' => [
            LogLevel::ALERT
        ]
    ]
]);
`
这种写法无法自定义log_level。
当然，
`
$app->getContainer()->get(ConfigInterface::class)->set(StdoutLoggerInterface::class, [
    'log_level' => [
        LogLevel::ALERT
    ]
]);
` 这种写法是可以的。

个人建议  https://github.com/hyperf/nano/blob/master/src/App.php#L318   将array_merge_recursive 改为  array_merge

**Comment by Reasno** [comment]
这个比较难抉择 两种写法各有优缺点

**Comment by xiaoguo0426** [comment]
> 这个比较难抉择 两种写法各有优缺点

个人觉得还是用第一种写法会好点吧~~
