### ISSUE TITLE
nano 自定义进程无效

### ISSUE THREAD

**Issue by phplim** [hyperf/nano#66]
用的是master分支，直接运行demo代码。等半天都没任何动作，不知道是哪个环节出了问题，就是不动。composer包都是最新的

![微信截图_20230925172336](https://github.com/hyperf/nano/assets/31526170/3c962039-4ec3-41bd-bc36-e03717c7b250)

**Comment by xuanyanwow** [comment]
```php
$app->addProcess(function(){
    while (true) {
        sleep(1);
        $this->container->get(StdoutLoggerInterface::class)->info('Processing...');
    }
})->setName('nano-process')->setNums(1)->setEnable(true);
```

**Comment by xuanyanwow** [comment]
Fixed https://github.com/hyperf/nano/pull/67
