### ISSUE TITLE
addCrontab 添加的定时任务没有执行

### ISSUE THREAD

**Issue by vincent66666** [hyperf/nano#8]
$app->addCrontab('* * * * * *', function(){
    $this->get(StdoutLoggerInterface::class)->info('execute every second!');
});
addCrontab 添加的定时任务没有运行执行

**Comment by Reasno** [comment]
第一个整分之后才会开始执行 和hyperf一样。

**Comment by Reasno** [comment]
会在下一个整分之后开始执行 和hyperf一样。

发自我的iPhone

**Comment by ajitrishabh** [comment]
Hi Reasno,
can you help me how i can run this in background of my application hosted on Cloud foundry?

**Comment by Reasno** [comment]
> Hi Reasno,
> can you help me how i can run this in background of my application hosted on Cloud foundry?

You can try the official docker image provided by hyperf. Just change the entry point to whatever you need.

https://github.com/hyperf/hyperf-docker
