### ISSUE TITLE
[Question] Implementation of Hyperf View in Nano

### ISSUE THREAD

**Issue by ljfreelancer88** [hyperf/nano#9]
Hi, how can I implement the Hyperf `view` to render page in Nano? Since the structure of configuration of Hyperf and Nano is different.

Thanks in advance.

**Comment by Reasno** [comment]
It is no different from standard hyperf. 

```php
    $app->config([ 'view' => [ 'engine' => BladeEngine::class]);
    $app->get('/', function(RenderInterface $render){
        return $render->render('index', ['name' => 'Hyperf']);
    });
```

Remember to require hyperf/view first.

**Comment by ljfreelancer88** [comment]
Thank you but how about the static resources configuration? Where to put this exactly?

**Comment by ljfreelancer88** [comment]
I got also this `Missing Task Worker processes, please set server.settings.task_worker_num before use task.` error. But I'm not sure where to set this.

**Comment by Reasno** [comment]
Put all relevant configurations in $app->config(). They follow the same structure in standard hyperf, except that the top-level keys are mapped from file names.  

For example
```php
$app->config([
    'view' => [
         'engine' => BladeEngine::class
    ],
    'task' => [
        'settings' => [
            'task_worker_num' => 8,
            'task_enable_coroutine' => false,
        ],
        'callbacks' => [
            // Task callbacks
            SwooleEvent::ON_TASK => [Hyperf\Framework\Bootstrap\TaskCallback::class, 'onTask'],
            SwooleEvent::ON_FINISH => [Hyperf\Framework\Bootstrap\FinishCallback::class, 'onFinish'],
        ],
    ],
    'server' => [
        'settings' => [
            'document_root' => BASE_PATH . '/public',
            'enable_static_handler' => true,
        ],
    ]
]);
```

**Comment by ljfreelancer88** [comment]
I've tried to configuration below but got this `Missing Task Worker processes, please set server.settings.task_worker_num before use task` error.

```
$app->config([
    'db.default' => [
        'host' => env('DB_HOST', 'localhost'),
        'port' => env('DB_PORT', 3306),
        'database' => env('DB_DATABASE', 'nano'),
        'username' => env('DB_USERNAME', 'username'),
        'password' => env('DB_PASSWORD', 'password'),
    ],
    'view' => [
    	'engine' => BladeEngine::class,
    ],
    'task' => [
        'settings' => [
            'task_worker_num' => 8,
            'task_enable_coroutine' => false,
        ],
        'callbacks' => [
            SwooleEvent::ON_TASK => [Hyperf\Framework\Bootstrap\TaskCallback::class, 'onTask'],
            SwooleEvent::ON_FINISH => [Hyperf\Framework\Bootstrap\FinishCallback::class, 'onFinish'],
        ],
    ],
    'server' => [
        'settings' => [
            'document_root' => __DIR__ . '/public',
            'enable_static_handler' => true,
        ],
    ]
]);
```

**Comment by limingxinleo** [comment]
'engine' => BladeEngine::class,
'mode' => Mode::SYNC,

**Comment by Reasno** [comment]
hyperf/task are required unless you use 'mode' => Mode::SYNC,

**Comment by ljfreelancer88** [comment]
Sorry but `'mode' => Mode::SYNC` still doesn't work. Still giving me the same error.

**Comment by Reasno** [comment]
I see no reason why it is not working. Here is a working/tested demo: https://github.com/Reasno/nano-demo

**Comment by ljfreelancer88** [comment]
I've tried your demo, still got the same error. I switched back trying the basic example, it's weird because it suppose to work but again the same error.

![Screenshot from 2020-07-17 10-44-58](https://user-images.githubusercontent.com/7919039/87799326-1332f400-c81b-11ea-900a-71887e690859.png)

**Comment by Reasno** [comment]
composer remove hyperf/task

**Comment by ljfreelancer88** [comment]
`composer remove hyperf/task` works!
